on:
  workflow_dispatch: # allow jobs manual run
  release:
    types: [published]

jobs:
  generate-apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalasi modules
        run: yarn

      - name: make gradle executable
        run: chmod +x ./android/gradlew

      - name: generate apk
        run: |
          cd android
          ./gradlew assembleRelease
